version: '3.8'

services:
  backend:
    build: .
    container_name: airconcare-backend
    ports:
      - "8181:8181"
    depends_on:
      - postgres
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PSWD: ${DB_PSWD}
      DB_NAME: ${DB_NAME}
    volumes:
      - .:/app
    restart: always

  postgres:
    image: postgres:latest
    container_name: airconcare_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
